print("#########################")
print("#                       #")
print("# Akhmad Chaidar Ananda #")
print("#   2310817110015       #")
print("#                       #")
print("#########################")